// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: unollm.proto

package unollm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLMTokenCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalToken      int64 `protobuf:"varint,1,opt,name=total_token,json=totalToken,proto3" json:"total_token,omitempty"`
	PromptToken     int64 `protobuf:"varint,2,opt,name=prompt_token,json=promptToken,proto3" json:"prompt_token,omitempty"`
	CompletionToken int64 `protobuf:"varint,3,opt,name=completion_token,json=completionToken,proto3" json:"completion_token,omitempty"`
}

func (x *LLMTokenCount) Reset() {
	*x = LLMTokenCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unollm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMTokenCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMTokenCount) ProtoMessage() {}

func (x *LLMTokenCount) ProtoReflect() protoreflect.Message {
	mi := &file_unollm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMTokenCount.ProtoReflect.Descriptor instead.
func (*LLMTokenCount) Descriptor() ([]byte, []int) {
	return file_unollm_proto_rawDescGZIP(), []int{0}
}

func (x *LLMTokenCount) GetTotalToken() int64 {
	if x != nil {
		return x.TotalToken
	}
	return 0
}

func (x *LLMTokenCount) GetPromptToken() int64 {
	if x != nil {
		return x.PromptToken
	}
	return 0
}

func (x *LLMTokenCount) GetCompletionToken() int64 {
	if x != nil {
		return x.CompletionToken
	}
	return 0
}

type LLMChatCompletionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role    string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *LLMChatCompletionMessage) Reset() {
	*x = LLMChatCompletionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unollm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMChatCompletionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMChatCompletionMessage) ProtoMessage() {}

func (x *LLMChatCompletionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_unollm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMChatCompletionMessage.ProtoReflect.Descriptor instead.
func (*LLMChatCompletionMessage) Descriptor() ([]byte, []int) {
	return file_unollm_proto_rawDescGZIP(), []int{1}
}

func (x *LLMChatCompletionMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LLMChatCompletionMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type LLMRequestInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LlmApiType  string            `protobuf:"bytes,1,opt,name=llm_api_type,json=llmApiType,proto3" json:"llm_api_type,omitempty"`
	Model       string            `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Temperature float64           `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP        float64           `protobuf:"fixed64,4,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	TopK        float64           `protobuf:"fixed64,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Url         string            `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Token       string            `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	Metainfo    map[string]string `protobuf:"bytes,8,rep,name=metainfo,proto3" json:"metainfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LLMRequestInfo) Reset() {
	*x = LLMRequestInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unollm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRequestInfo) ProtoMessage() {}

func (x *LLMRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_unollm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRequestInfo.ProtoReflect.Descriptor instead.
func (*LLMRequestInfo) Descriptor() ([]byte, []int) {
	return file_unollm_proto_rawDescGZIP(), []int{2}
}

func (x *LLMRequestInfo) GetLlmApiType() string {
	if x != nil {
		return x.LlmApiType
	}
	return ""
}

func (x *LLMRequestInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMRequestInfo) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *LLMRequestInfo) GetTopP() float64 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *LLMRequestInfo) GetTopK() float64 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *LLMRequestInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LLMRequestInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LLMRequestInfo) GetMetainfo() map[string]string {
	if x != nil {
		return x.Metainfo
	}
	return nil
}

type LLMRequestSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages       []*LLMChatCompletionMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	LlmRequestInfo *LLMRequestInfo             `protobuf:"bytes,2,opt,name=llm_request_info,json=llmRequestInfo,proto3" json:"llm_request_info,omitempty"`
}

func (x *LLMRequestSchema) Reset() {
	*x = LLMRequestSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unollm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMRequestSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRequestSchema) ProtoMessage() {}

func (x *LLMRequestSchema) ProtoReflect() protoreflect.Message {
	mi := &file_unollm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRequestSchema.ProtoReflect.Descriptor instead.
func (*LLMRequestSchema) Descriptor() ([]byte, []int) {
	return file_unollm_proto_rawDescGZIP(), []int{3}
}

func (x *LLMRequestSchema) GetMessages() []*LLMChatCompletionMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *LLMRequestSchema) GetLlmRequestInfo() *LLMRequestInfo {
	if x != nil {
		return x.LlmRequestInfo
	}
	return nil
}

type LLMResponseSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message       *LLMChatCompletionMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	LlmTokenCount *LLMTokenCount            `protobuf:"bytes,2,opt,name=llm_token_count,json=llmTokenCount,proto3" json:"llm_token_count,omitempty"`
}

func (x *LLMResponseSchema) Reset() {
	*x = LLMResponseSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unollm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LLMResponseSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMResponseSchema) ProtoMessage() {}

func (x *LLMResponseSchema) ProtoReflect() protoreflect.Message {
	mi := &file_unollm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMResponseSchema.ProtoReflect.Descriptor instead.
func (*LLMResponseSchema) Descriptor() ([]byte, []int) {
	return file_unollm_proto_rawDescGZIP(), []int{4}
}

func (x *LLMResponseSchema) GetMessage() *LLMChatCompletionMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *LLMResponseSchema) GetLlmTokenCount() *LLMTokenCount {
	if x != nil {
		return x.LlmTokenCount
	}
	return nil
}

type Done struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Done) Reset() {
	*x = Done{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unollm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_unollm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_unollm_proto_rawDescGZIP(), []int{5}
}

type PartialLLMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*PartialLLMResponse_Content
	//	*PartialLLMResponse_Done
	Response      isPartialLLMResponse_Response `protobuf_oneof:"response"`
	LlmTokenCount *LLMTokenCount                `protobuf:"bytes,3,opt,name=llm_token_count,json=llmTokenCount,proto3,oneof" json:"llm_token_count,omitempty"`
}

func (x *PartialLLMResponse) Reset() {
	*x = PartialLLMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unollm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialLLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialLLMResponse) ProtoMessage() {}

func (x *PartialLLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unollm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialLLMResponse.ProtoReflect.Descriptor instead.
func (*PartialLLMResponse) Descriptor() ([]byte, []int) {
	return file_unollm_proto_rawDescGZIP(), []int{6}
}

func (m *PartialLLMResponse) GetResponse() isPartialLLMResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *PartialLLMResponse) GetContent() string {
	if x, ok := x.GetResponse().(*PartialLLMResponse_Content); ok {
		return x.Content
	}
	return ""
}

func (x *PartialLLMResponse) GetDone() *Done {
	if x, ok := x.GetResponse().(*PartialLLMResponse_Done); ok {
		return x.Done
	}
	return nil
}

func (x *PartialLLMResponse) GetLlmTokenCount() *LLMTokenCount {
	if x != nil {
		return x.LlmTokenCount
	}
	return nil
}

type isPartialLLMResponse_Response interface {
	isPartialLLMResponse_Response()
}

type PartialLLMResponse_Content struct {
	Content string `protobuf:"bytes,1,opt,name=content,proto3,oneof"`
}

type PartialLLMResponse_Done struct {
	Done *Done `protobuf:"bytes,2,opt,name=done,proto3,oneof"`
}

func (*PartialLLMResponse_Content) isPartialLLMResponse_Response() {}

func (*PartialLLMResponse_Done) isPartialLLMResponse_Response() {}

var File_unollm_proto protoreflect.FileDescriptor

var file_unollm_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x75, 0x6e, 0x6f, 0x6c, 0x6c, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x75, 0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x22, 0x7e, 0x0a, 0x0d, 0x4c, 0x4c, 0x4d, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6d,
	0x70, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x48, 0x0a, 0x18, 0x4c, 0x4c, 0x4d, 0x43, 0x68, 0x61,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0xbb, 0x02, 0x0a, 0x0e, 0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x6c, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6c, 0x6d, 0x41, 0x70,
	0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x74,
	0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x13, 0x0a,
	0x05, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x6f,
	0x70, 0x50, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x5f, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x04, 0x74, 0x6f, 0x70, 0x4b, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x75, 0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x4c, 0x4c, 0x4d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x69, 0x6e,
	0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x66,
	0x6f, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x69, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x92,
	0x01, 0x0a, 0x10, 0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x12, 0x3c, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x75, 0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x4c,
	0x4c, 0x4d, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x40, 0x0a, 0x10, 0x6c, 0x6c, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x75, 0x6e,
	0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x6c, 0x6c, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x11, 0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x3a, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x75, 0x6e, 0x6f,
	0x4c, 0x4c, 0x4d, 0x2e, 0x4c, 0x4c, 0x4d, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x6c, 0x6c, 0x6d, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x75, 0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x4c, 0x4c, 0x4d, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0d, 0x6c, 0x6c, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x06, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x22, 0xb8, 0x01, 0x0a,
	0x12, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x22, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x75, 0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x44, 0x6f, 0x6e, 0x65, 0x48, 0x00, 0x52, 0x04, 0x64,
	0x6f, 0x6e, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x6c, 0x6c, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75,
	0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x4c, 0x4c, 0x4d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x48, 0x01, 0x52, 0x0d, 0x6c, 0x6c, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x6c, 0x6c, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xa5, 0x01, 0x0a, 0x08, 0x55, 0x6e, 0x6f, 0x4c,
	0x4c, 0x4d, 0x76, 0x31, 0x12, 0x4b, 0x0a, 0x12, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x4c, 0x4d, 0x12, 0x18, 0x2e, 0x75, 0x6e, 0x6f,
	0x4c, 0x4c, 0x4d, 0x2e, 0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x1a, 0x19, 0x2e, 0x75, 0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x4c, 0x4c,
	0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4c, 0x4c, 0x4d, 0x12, 0x18, 0x2e, 0x75, 0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x4c,
	0x4c, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a,
	0x1a, 0x2e, 0x75, 0x6e, 0x6f, 0x4c, 0x4c, 0x4d, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c,
	0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x75, 0x6e, 0x6f, 0x6c, 0x6c, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_unollm_proto_rawDescOnce sync.Once
	file_unollm_proto_rawDescData = file_unollm_proto_rawDesc
)

func file_unollm_proto_rawDescGZIP() []byte {
	file_unollm_proto_rawDescOnce.Do(func() {
		file_unollm_proto_rawDescData = protoimpl.X.CompressGZIP(file_unollm_proto_rawDescData)
	})
	return file_unollm_proto_rawDescData
}

var file_unollm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_unollm_proto_goTypes = []interface{}{
	(*LLMTokenCount)(nil),            // 0: unoLLM.LLMTokenCount
	(*LLMChatCompletionMessage)(nil), // 1: unoLLM.LLMChatCompletionMessage
	(*LLMRequestInfo)(nil),           // 2: unoLLM.LLMRequestInfo
	(*LLMRequestSchema)(nil),         // 3: unoLLM.LLMRequestSchema
	(*LLMResponseSchema)(nil),        // 4: unoLLM.LLMResponseSchema
	(*Done)(nil),                     // 5: unoLLM.Done
	(*PartialLLMResponse)(nil),       // 6: unoLLM.PartialLLMResponse
	nil,                              // 7: unoLLM.LLMRequestInfo.MetainfoEntry
}
var file_unollm_proto_depIdxs = []int32{
	7, // 0: unoLLM.LLMRequestInfo.metainfo:type_name -> unoLLM.LLMRequestInfo.MetainfoEntry
	1, // 1: unoLLM.LLMRequestSchema.messages:type_name -> unoLLM.LLMChatCompletionMessage
	2, // 2: unoLLM.LLMRequestSchema.llm_request_info:type_name -> unoLLM.LLMRequestInfo
	1, // 3: unoLLM.LLMResponseSchema.message:type_name -> unoLLM.LLMChatCompletionMessage
	0, // 4: unoLLM.LLMResponseSchema.llm_token_count:type_name -> unoLLM.LLMTokenCount
	5, // 5: unoLLM.PartialLLMResponse.done:type_name -> unoLLM.Done
	0, // 6: unoLLM.PartialLLMResponse.llm_token_count:type_name -> unoLLM.LLMTokenCount
	3, // 7: unoLLM.UnoLLMv1.BlockingRequestLLM:input_type -> unoLLM.LLMRequestSchema
	3, // 8: unoLLM.UnoLLMv1.StreamRequestLLM:input_type -> unoLLM.LLMRequestSchema
	4, // 9: unoLLM.UnoLLMv1.BlockingRequestLLM:output_type -> unoLLM.LLMResponseSchema
	6, // 10: unoLLM.UnoLLMv1.StreamRequestLLM:output_type -> unoLLM.PartialLLMResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_unollm_proto_init() }
func file_unollm_proto_init() {
	if File_unollm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unollm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMTokenCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unollm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMChatCompletionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unollm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMRequestInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unollm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMRequestSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unollm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LLMResponseSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unollm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Done); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unollm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartialLLMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_unollm_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*PartialLLMResponse_Content)(nil),
		(*PartialLLMResponse_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unollm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unollm_proto_goTypes,
		DependencyIndexes: file_unollm_proto_depIdxs,
		MessageInfos:      file_unollm_proto_msgTypes,
	}.Build()
	File_unollm_proto = out.File
	file_unollm_proto_rawDesc = nil
	file_unollm_proto_goTypes = nil
	file_unollm_proto_depIdxs = nil
}
