openapi: 3.0.1
info:
  description: ""
  title: UnoLLM
  version: 1.0.0
servers:
- url: /
tags:
- name: /keyStore
- name: /user
paths:
  /keyStore/addKey:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              key: mollit cupidatat ipsum est dolor
              provider: chatglm
              endpoint: officia
            schema:
              $ref: '#/components/schemas/_keyStore_addKey_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_keyStore_addKey_post_200_response'
          description: 成功
      security: []
      summary: "/addKey: 新增API KEY"
      tags: []
      x-apifox-folder: ""
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605554-run
  /keyStore/mapTo:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_keyStore_mapTo_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      security: []
      summary: "/mapTo: 映射APIKey到用户定义Key"
      tags: []
      x-apifox-folder: ""
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605555-run
  /keyStore/keys:
    get:
      deprecated: false
      description: ""
      parameters: []
      responses:
        "200":
          content:
            application/json:
              examples:
                "1":
                  summary: 成功示例
                  value:
                  - id: 0
                    key: string
                    endpoint: string
              schema:
                items:
                  $ref: '#/components/schemas/_keyStore_keys_get_200_response_inner'
                type: array
          description: 成功
      security: []
      summary: "/keys: 获取全部原始Key"
      tags: []
      x-apifox-folder: ""
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605556-run
  /keyStore/newApi:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_keyStore_newApi_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      security: []
      summary: "/newApi: 新建用户定义的API Key"
      tags: []
      x-apifox-folder: ""
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605557-run
  /keyStore/testTransformer:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              key: 94a6fe9b-3022-4405-bc16-87f88f332863
              provider: "65"
            schema:
              $ref: '#/components/schemas/_keyStore_testTransformer_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_keyStore_testTransformer_post_200_response'
          description: 成功
      security:
      - apikey-header-Authorization: []
      summary: 测试APIKey映射
      tags:
      - /keyStore
      x-apifox-folder: /keyStore
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605594-run
  /keyStore/userDefinedKeys:
    get:
      deprecated: false
      description: ""
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_keyStore_userDefinedKeys_get_200_response_inner'
                type: array
          description: 成功
      security:
      - apikey-header-Authorization: []
      summary: 获取用户定义API Key表列
      tags:
      - /keyStore
      x-apifox-folder: /keyStore
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605601-run
  /keyStore/removeMapTo:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            example:
              keys:
              - 1
              mapTo: 1
            schema:
              $ref: '#/components/schemas/MapTo'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      security:
      - apikey-header-Authorization: []
      summary: 删除现有映射
      tags:
      - /keyStore
      x-apifox-folder: /keyStore
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605605-run
  /user/create:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_user_create_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties: {}
                type: object
                x-apifox-ignore-properties: []
                x-apifox-orders: []
          description: 成功
      security: []
      summary: 创建用户
      tags:
      - /user
      x-apifox-folder: /user
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605838-run
  /user/login:
    post:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_user_create_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_user_login_post_200_response'
          description: 成功
      security:
      - apikey-header-Authorization: []
      summary: 登陆
      tags:
      - /user
      x-apifox-folder: /user
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605839-run
  /user/logout:
    get:
      deprecated: false
      description: ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_user_create_post_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_user_login_post_200_response'
          description: 成功
      security:
      - apikey-header-Authorization: []
      summary: 登出
      tags:
      - /user
      x-apifox-folder: /user
      x-apifox-status: developing
      x-run-in-apifox: https://apifox.com/web/project/3683578/apis/api-129605849-run
components:
  schemas:
    MapTo:
      example:
        keys:
        - 0
        - 0
        mapTo: 6
      properties:
        keys:
          items:
            type: integer
          title: Key ID
          type: array
        mapTo:
          title: Key ID
          type: integer
      required:
      - keys
      - mapTo
      type: object
      x-apifox-orders:
      - keys
      - mapTo
      x-apifox-ignore-properties: []
      x-apifox-folder: ""
    _keyStore_addKey_post_request:
      properties:
        key:
          type: string
        provider:
          description: ChatGLM | ChatGPT
          enum:
          - chatglm
          - chatgpt
          type: string
          x-apifox:
            enumDescriptions:
              chatglm: ""
              chatgpt: ""
        endpoint:
          nullable: true
          type: string
      required:
      - key
      - provider
      type: object
      x-apifox-orders:
      - key
      - provider
      - endpoint
      x-apifox-ignore-properties: []
    _keyStore_addKey_post_200_response:
      example:
        id: 0
      properties:
        id:
          type: integer
      required:
      - id
      type: object
      x-apifox-orders:
      - id
      x-apifox-ignore-properties: []
    _keyStore_mapTo_post_request:
      properties:
        keys:
          description: APIKey的ID
          items:
            type: integer
          type: array
        mapTo:
          description: 目标Key
          type: integer
      required:
      - keys
      - mapTo
      type: object
      x-apifox-orders:
      - keys
      - mapTo
      x-apifox-ignore-properties: []
    _keyStore_keys_get_200_response_inner:
      example:
        endpoint: endpoint
        provider: chatglm
        id: 0
        key: key
      properties:
        id:
          type: integer
        key:
          type: string
        endpoint:
          nullable: true
          type: string
        provider:
          enum:
          - chatglm
          - chatgpt
          type: string
          x-apifox:
            enumDescriptions:
              chatglm: ""
              chatgpt: ""
      required:
      - id
      - key
      - provider
      type: object
      x-apifox-orders:
      - id
      - key
      - endpoint
      - provider
      x-apifox-ignore-properties: []
    _keyStore_newApi_post_request:
      properties:
        key:
          nullable: true
          type: string
      type: object
      x-apifox-orders:
      - key
      x-apifox-ignore-properties: []
    _keyStore_testTransformer_post_request:
      properties:
        key:
          type: string
        provider:
          type: string
      required:
      - key
      - provider
      type: object
      x-apifox-orders:
      - key
      - provider
      x-apifox-ignore-properties: []
    _keyStore_testTransformer_post_200_response:
      example:
        endpoint: endpoint
        key: key
      properties:
        endpoint:
          nullable: true
          type: string
        key:
          type: string
      required:
      - key
      type: object
      x-apifox-orders:
      - endpoint
      - key
      x-apifox-ignore-properties: []
    _keyStore_userDefinedKeys_get_200_response_inner:
      example:
        key: key
      properties:
        key:
          type: string
      required:
      - key
      type: object
      x-apifox-orders:
      - key
      x-apifox-ignore-properties: []
    _user_create_post_request:
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - password
      - username
      type: object
      x-apifox-orders:
      - username
      - password
      x-apifox-ignore-properties: []
    _user_login_post_200_response:
      example:
        token: token
      properties:
        token:
          type: string
      required:
      - token
      type: object
      x-apifox-orders:
      - token
      x-apifox-ignore-properties: []
  securitySchemes:
    apikey-header-Authorization:
      in: header
      name: Authorization
      type: apiKey
