/*
UnoLLM

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apimodel

import (
	"encoding/json"
	"fmt"
)

// checks if the KeyStoreAddKeyPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyStoreAddKeyPost200Response{}

// KeyStoreAddKeyPost200Response struct for KeyStoreAddKeyPost200Response
type KeyStoreAddKeyPost200Response struct {
	Id int32 `json:"id"`
}

type _KeyStoreAddKeyPost200Response KeyStoreAddKeyPost200Response

// NewKeyStoreAddKeyPost200Response instantiates a new KeyStoreAddKeyPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyStoreAddKeyPost200Response(id int32) *KeyStoreAddKeyPost200Response {
	this := KeyStoreAddKeyPost200Response{}
	this.Id = id
	return &this
}

// NewKeyStoreAddKeyPost200ResponseWithDefaults instantiates a new KeyStoreAddKeyPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyStoreAddKeyPost200ResponseWithDefaults() *KeyStoreAddKeyPost200Response {
	this := KeyStoreAddKeyPost200Response{}
	return &this
}

// GetId returns the Id field value
func (o *KeyStoreAddKeyPost200Response) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KeyStoreAddKeyPost200Response) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KeyStoreAddKeyPost200Response) SetId(v int32) {
	o.Id = v
}

func (o KeyStoreAddKeyPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyStoreAddKeyPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *KeyStoreAddKeyPost200Response) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyStoreAddKeyPost200Response := _KeyStoreAddKeyPost200Response{}

	err = json.Unmarshal(bytes, &varKeyStoreAddKeyPost200Response)

	if err != nil {
		return err
	}

	*o = KeyStoreAddKeyPost200Response(varKeyStoreAddKeyPost200Response)

	return err
}

type NullableKeyStoreAddKeyPost200Response struct {
	value *KeyStoreAddKeyPost200Response
	isSet bool
}

func (v NullableKeyStoreAddKeyPost200Response) Get() *KeyStoreAddKeyPost200Response {
	return v.value
}

func (v *NullableKeyStoreAddKeyPost200Response) Set(val *KeyStoreAddKeyPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyStoreAddKeyPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyStoreAddKeyPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyStoreAddKeyPost200Response(val *KeyStoreAddKeyPost200Response) *NullableKeyStoreAddKeyPost200Response {
	return &NullableKeyStoreAddKeyPost200Response{value: val, isSet: true}
}

func (v NullableKeyStoreAddKeyPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyStoreAddKeyPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
