/*
UnoLLM

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apimodel

import (
	"encoding/json"
	"fmt"
)

// checks if the MapTo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapTo{}

// MapTo struct for MapTo
type MapTo struct {
	Keys  []int32 `json:"keys"`
	MapTo int32   `json:"mapTo"`
}

type _MapTo MapTo

// NewMapTo instantiates a new MapTo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapTo(keys []int32, mapTo int32) *MapTo {
	this := MapTo{}
	this.Keys = keys
	this.MapTo = mapTo
	return &this
}

// NewMapToWithDefaults instantiates a new MapTo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapToWithDefaults() *MapTo {
	this := MapTo{}
	return &this
}

// GetKeys returns the Keys field value
func (o *MapTo) GetKeys() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *MapTo) GetKeysOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *MapTo) SetKeys(v []int32) {
	o.Keys = v
}

// GetMapTo returns the MapTo field value
func (o *MapTo) GetMapTo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MapTo
}

// GetMapToOk returns a tuple with the MapTo field value
// and a boolean to check if the value has been set.
func (o *MapTo) GetMapToOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MapTo, true
}

// SetMapTo sets field value
func (o *MapTo) SetMapTo(v int32) {
	o.MapTo = v
}

func (o MapTo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapTo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keys"] = o.Keys
	toSerialize["mapTo"] = o.MapTo
	return toSerialize, nil
}

func (o *MapTo) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keys",
		"mapTo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMapTo := _MapTo{}

	err = json.Unmarshal(bytes, &varMapTo)

	if err != nil {
		return err
	}

	*o = MapTo(varMapTo)

	return err
}

type NullableMapTo struct {
	value *MapTo
	isSet bool
}

func (v NullableMapTo) Get() *MapTo {
	return v.value
}

func (v *NullableMapTo) Set(val *MapTo) {
	v.value = val
	v.isSet = true
}

func (v NullableMapTo) IsSet() bool {
	return v.isSet
}

func (v *NullableMapTo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapTo(val *MapTo) *NullableMapTo {
	return &NullableMapTo{value: val, isSet: true}
}

func (v NullableMapTo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapTo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
