/*
UnoLLM

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apimodel

import (
	"encoding/json"
	"fmt"
)

// checks if the KeyStoreKeysGetRequestInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyStoreKeysGetRequestInner{}

// KeyStoreKeysGetRequestInner struct for KeyStoreKeysGetRequestInner
type KeyStoreKeysGetRequestInner struct {
	Id       int32          `json:"id"`
	Key      string         `json:"key"`
	Endpoint NullableString `json:"endpoint,omitempty"`
}

type _KeyStoreKeysGetRequestInner KeyStoreKeysGetRequestInner

// NewKeyStoreKeysGetRequestInner instantiates a new KeyStoreKeysGetRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyStoreKeysGetRequestInner(id int32, key string) *KeyStoreKeysGetRequestInner {
	this := KeyStoreKeysGetRequestInner{}
	this.Id = id
	this.Key = key
	return &this
}

// NewKeyStoreKeysGetRequestInnerWithDefaults instantiates a new KeyStoreKeysGetRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyStoreKeysGetRequestInnerWithDefaults() *KeyStoreKeysGetRequestInner {
	this := KeyStoreKeysGetRequestInner{}
	return &this
}

// GetId returns the Id field value
func (o *KeyStoreKeysGetRequestInner) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KeyStoreKeysGetRequestInner) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KeyStoreKeysGetRequestInner) SetId(v int32) {
	o.Id = v
}

// GetKey returns the Key field value
func (o *KeyStoreKeysGetRequestInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *KeyStoreKeysGetRequestInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *KeyStoreKeysGetRequestInner) SetKey(v string) {
	o.Key = v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyStoreKeysGetRequestInner) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint.Get()) {
		var ret string
		return ret
	}
	return *o.Endpoint.Get()
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyStoreKeysGetRequestInner) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoint.Get(), o.Endpoint.IsSet()
}

// HasEndpoint returns a boolean if a field has been set.
func (o *KeyStoreKeysGetRequestInner) HasEndpoint() bool {
	if o != nil && o.Endpoint.IsSet() {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given NullableString and assigns it to the Endpoint field.
func (o *KeyStoreKeysGetRequestInner) SetEndpoint(v string) {
	o.Endpoint.Set(&v)
}

// SetEndpointNil sets the value for Endpoint to be an explicit nil
func (o *KeyStoreKeysGetRequestInner) SetEndpointNil() {
	o.Endpoint.Set(nil)
}

// UnsetEndpoint ensures that no value is present for Endpoint, not even an explicit nil
func (o *KeyStoreKeysGetRequestInner) UnsetEndpoint() {
	o.Endpoint.Unset()
}

func (o KeyStoreKeysGetRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyStoreKeysGetRequestInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["key"] = o.Key
	if o.Endpoint.IsSet() {
		toSerialize["endpoint"] = o.Endpoint.Get()
	}
	return toSerialize, nil
}

func (o *KeyStoreKeysGetRequestInner) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyStoreKeysGetRequestInner := _KeyStoreKeysGetRequestInner{}

	err = json.Unmarshal(bytes, &varKeyStoreKeysGetRequestInner)

	if err != nil {
		return err
	}

	*o = KeyStoreKeysGetRequestInner(varKeyStoreKeysGetRequestInner)

	return err
}

type NullableKeyStoreKeysGetRequestInner struct {
	value *KeyStoreKeysGetRequestInner
	isSet bool
}

func (v NullableKeyStoreKeysGetRequestInner) Get() *KeyStoreKeysGetRequestInner {
	return v.value
}

func (v *NullableKeyStoreKeysGetRequestInner) Set(val *KeyStoreKeysGetRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyStoreKeysGetRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyStoreKeysGetRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyStoreKeysGetRequestInner(val *KeyStoreKeysGetRequestInner) *NullableKeyStoreKeysGetRequestInner {
	return &NullableKeyStoreKeysGetRequestInner{value: val, isSet: true}
}

func (v NullableKeyStoreKeysGetRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyStoreKeysGetRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
