/*
UnoLLM

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apimodel

import (
	"encoding/json"
)

// checks if the KeyStoreNewApiPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyStoreNewApiPostRequest{}

// KeyStoreNewApiPostRequest struct for KeyStoreNewApiPostRequest
type KeyStoreNewApiPostRequest struct {
	Key NullableString `json:"key,omitempty"`
}

// NewKeyStoreNewApiPostRequest instantiates a new KeyStoreNewApiPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyStoreNewApiPostRequest() *KeyStoreNewApiPostRequest {
	this := KeyStoreNewApiPostRequest{}
	return &this
}

// NewKeyStoreNewApiPostRequestWithDefaults instantiates a new KeyStoreNewApiPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyStoreNewApiPostRequestWithDefaults() *KeyStoreNewApiPostRequest {
	this := KeyStoreNewApiPostRequest{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyStoreNewApiPostRequest) GetKey() string {
	if o == nil || IsNil(o.Key.Get()) {
		var ret string
		return ret
	}
	return *o.Key.Get()
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyStoreNewApiPostRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Key.Get(), o.Key.IsSet()
}

// HasKey returns a boolean if a field has been set.
func (o *KeyStoreNewApiPostRequest) HasKey() bool {
	if o != nil && o.Key.IsSet() {
		return true
	}

	return false
}

// SetKey gets a reference to the given NullableString and assigns it to the Key field.
func (o *KeyStoreNewApiPostRequest) SetKey(v string) {
	o.Key.Set(&v)
}

// SetKeyNil sets the value for Key to be an explicit nil
func (o *KeyStoreNewApiPostRequest) SetKeyNil() {
	o.Key.Set(nil)
}

// UnsetKey ensures that no value is present for Key, not even an explicit nil
func (o *KeyStoreNewApiPostRequest) UnsetKey() {
	o.Key.Unset()
}

func (o KeyStoreNewApiPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyStoreNewApiPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Key.IsSet() {
		toSerialize["key"] = o.Key.Get()
	}
	return toSerialize, nil
}

type NullableKeyStoreNewApiPostRequest struct {
	value *KeyStoreNewApiPostRequest
	isSet bool
}

func (v NullableKeyStoreNewApiPostRequest) Get() *KeyStoreNewApiPostRequest {
	return v.value
}

func (v *NullableKeyStoreNewApiPostRequest) Set(val *KeyStoreNewApiPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyStoreNewApiPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyStoreNewApiPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyStoreNewApiPostRequest(val *KeyStoreNewApiPostRequest) *NullableKeyStoreNewApiPostRequest {
	return &NullableKeyStoreNewApiPostRequest{value: val, isSet: true}
}

func (v NullableKeyStoreNewApiPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyStoreNewApiPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
