/*
UnoLLM

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apimodel

import (
	"encoding/json"
	"fmt"
)

// checks if the KeyStoreTestTransformerPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyStoreTestTransformerPost200Response{}

// KeyStoreTestTransformerPost200Response struct for KeyStoreTestTransformerPost200Response
type KeyStoreTestTransformerPost200Response struct {
	Endpoint NullableString `json:"endpoint,omitempty"`
	Key      string         `json:"key"`
}

type _KeyStoreTestTransformerPost200Response KeyStoreTestTransformerPost200Response

// NewKeyStoreTestTransformerPost200Response instantiates a new KeyStoreTestTransformerPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyStoreTestTransformerPost200Response(key string) *KeyStoreTestTransformerPost200Response {
	this := KeyStoreTestTransformerPost200Response{}
	this.Key = key
	return &this
}

// NewKeyStoreTestTransformerPost200ResponseWithDefaults instantiates a new KeyStoreTestTransformerPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyStoreTestTransformerPost200ResponseWithDefaults() *KeyStoreTestTransformerPost200Response {
	this := KeyStoreTestTransformerPost200Response{}
	return &this
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KeyStoreTestTransformerPost200Response) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint.Get()) {
		var ret string
		return ret
	}
	return *o.Endpoint.Get()
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KeyStoreTestTransformerPost200Response) GetEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Endpoint.Get(), o.Endpoint.IsSet()
}

// HasEndpoint returns a boolean if a field has been set.
func (o *KeyStoreTestTransformerPost200Response) HasEndpoint() bool {
	if o != nil && o.Endpoint.IsSet() {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given NullableString and assigns it to the Endpoint field.
func (o *KeyStoreTestTransformerPost200Response) SetEndpoint(v string) {
	o.Endpoint.Set(&v)
}

// SetEndpointNil sets the value for Endpoint to be an explicit nil
func (o *KeyStoreTestTransformerPost200Response) SetEndpointNil() {
	o.Endpoint.Set(nil)
}

// UnsetEndpoint ensures that no value is present for Endpoint, not even an explicit nil
func (o *KeyStoreTestTransformerPost200Response) UnsetEndpoint() {
	o.Endpoint.Unset()
}

// GetKey returns the Key field value
func (o *KeyStoreTestTransformerPost200Response) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *KeyStoreTestTransformerPost200Response) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *KeyStoreTestTransformerPost200Response) SetKey(v string) {
	o.Key = v
}

func (o KeyStoreTestTransformerPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyStoreTestTransformerPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Endpoint.IsSet() {
		toSerialize["endpoint"] = o.Endpoint.Get()
	}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *KeyStoreTestTransformerPost200Response) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyStoreTestTransformerPost200Response := _KeyStoreTestTransformerPost200Response{}

	err = json.Unmarshal(bytes, &varKeyStoreTestTransformerPost200Response)

	if err != nil {
		return err
	}

	*o = KeyStoreTestTransformerPost200Response(varKeyStoreTestTransformerPost200Response)

	return err
}

type NullableKeyStoreTestTransformerPost200Response struct {
	value *KeyStoreTestTransformerPost200Response
	isSet bool
}

func (v NullableKeyStoreTestTransformerPost200Response) Get() *KeyStoreTestTransformerPost200Response {
	return v.value
}

func (v *NullableKeyStoreTestTransformerPost200Response) Set(val *KeyStoreTestTransformerPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyStoreTestTransformerPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyStoreTestTransformerPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyStoreTestTransformerPost200Response(val *KeyStoreTestTransformerPost200Response) *NullableKeyStoreTestTransformerPost200Response {
	return &NullableKeyStoreTestTransformerPost200Response{value: val, isSet: true}
}

func (v NullableKeyStoreTestTransformerPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyStoreTestTransformerPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
