/*
UnoLLM

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apimodel

import (
	"encoding/json"
	"fmt"
)

// checks if the KeyStoreUserDefinedKeysGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyStoreUserDefinedKeysGet200ResponseInner{}

// KeyStoreUserDefinedKeysGet200ResponseInner struct for KeyStoreUserDefinedKeysGet200ResponseInner
type KeyStoreUserDefinedKeysGet200ResponseInner struct {
	Key string `json:"key"`
}

type _KeyStoreUserDefinedKeysGet200ResponseInner KeyStoreUserDefinedKeysGet200ResponseInner

// NewKeyStoreUserDefinedKeysGet200ResponseInner instantiates a new KeyStoreUserDefinedKeysGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyStoreUserDefinedKeysGet200ResponseInner(key string) *KeyStoreUserDefinedKeysGet200ResponseInner {
	this := KeyStoreUserDefinedKeysGet200ResponseInner{}
	this.Key = key
	return &this
}

// NewKeyStoreUserDefinedKeysGet200ResponseInnerWithDefaults instantiates a new KeyStoreUserDefinedKeysGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyStoreUserDefinedKeysGet200ResponseInnerWithDefaults() *KeyStoreUserDefinedKeysGet200ResponseInner {
	this := KeyStoreUserDefinedKeysGet200ResponseInner{}
	return &this
}

// GetKey returns the Key field value
func (o *KeyStoreUserDefinedKeysGet200ResponseInner) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *KeyStoreUserDefinedKeysGet200ResponseInner) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *KeyStoreUserDefinedKeysGet200ResponseInner) SetKey(v string) {
	o.Key = v
}

func (o KeyStoreUserDefinedKeysGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyStoreUserDefinedKeysGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	return toSerialize, nil
}

func (o *KeyStoreUserDefinedKeysGet200ResponseInner) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyStoreUserDefinedKeysGet200ResponseInner := _KeyStoreUserDefinedKeysGet200ResponseInner{}

	err = json.Unmarshal(bytes, &varKeyStoreUserDefinedKeysGet200ResponseInner)

	if err != nil {
		return err
	}

	*o = KeyStoreUserDefinedKeysGet200ResponseInner(varKeyStoreUserDefinedKeysGet200ResponseInner)

	return err
}

type NullableKeyStoreUserDefinedKeysGet200ResponseInner struct {
	value *KeyStoreUserDefinedKeysGet200ResponseInner
	isSet bool
}

func (v NullableKeyStoreUserDefinedKeysGet200ResponseInner) Get() *KeyStoreUserDefinedKeysGet200ResponseInner {
	return v.value
}

func (v *NullableKeyStoreUserDefinedKeysGet200ResponseInner) Set(val *KeyStoreUserDefinedKeysGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyStoreUserDefinedKeysGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyStoreUserDefinedKeysGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyStoreUserDefinedKeysGet200ResponseInner(val *KeyStoreUserDefinedKeysGet200ResponseInner) *NullableKeyStoreUserDefinedKeysGet200ResponseInner {
	return &NullableKeyStoreUserDefinedKeysGet200ResponseInner{value: val, isSet: true}
}

func (v NullableKeyStoreUserDefinedKeysGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyStoreUserDefinedKeysGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
