/*
UnoLLM

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apimodel

import (
	"encoding/json"
	"fmt"
)

// checks if the UserCreatePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCreatePostRequest{}

// UserCreatePostRequest struct for UserCreatePostRequest
type UserCreatePostRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type _UserCreatePostRequest UserCreatePostRequest

// NewUserCreatePostRequest instantiates a new UserCreatePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCreatePostRequest(username string, password string) *UserCreatePostRequest {
	this := UserCreatePostRequest{}
	this.Username = username
	this.Password = password
	return &this
}

// NewUserCreatePostRequestWithDefaults instantiates a new UserCreatePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCreatePostRequestWithDefaults() *UserCreatePostRequest {
	this := UserCreatePostRequest{}
	return &this
}

// GetUsername returns the Username field value
func (o *UserCreatePostRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserCreatePostRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserCreatePostRequest) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *UserCreatePostRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UserCreatePostRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UserCreatePostRequest) SetPassword(v string) {
	o.Password = v
}

func (o UserCreatePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCreatePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *UserCreatePostRequest) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserCreatePostRequest := _UserCreatePostRequest{}

	err = json.Unmarshal(bytes, &varUserCreatePostRequest)

	if err != nil {
		return err
	}

	*o = UserCreatePostRequest(varUserCreatePostRequest)

	return err
}

type NullableUserCreatePostRequest struct {
	value *UserCreatePostRequest
	isSet bool
}

func (v NullableUserCreatePostRequest) Get() *UserCreatePostRequest {
	return v.value
}

func (v *NullableUserCreatePostRequest) Set(val *UserCreatePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCreatePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCreatePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCreatePostRequest(val *UserCreatePostRequest) *NullableUserCreatePostRequest {
	return &NullableUserCreatePostRequest{value: val, isSet: true}
}

func (v NullableUserCreatePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCreatePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
